### ISSUE TITLE
ArgumentError causes gradescope tests to fail?

### ISSUE THREAD

**Issue by d-gallagher** [gmit-sweng-20/ca2-sinatra-saas-d-gallagher#3]
Hi John,

I might be wrong about this but maybe you can take a quick look..
We need to raise this arg error https://github.com/gmit-sweng-20/ca2-sinatra-saas-d-gallagher/blob/efd5de9586f5a4e8d3156dc92e2c9229d78f6c64/lib/hangperson_game.rb#L24 to pass game logic tests for 'invalid' in the hangperson_game_spec.rb.
Those tests are passing as expected. 
However when testing a numeric/blank input in the app.rb '/guess', https://github.com/gmit-sweng-20/ca2-sinatra-saas-d-gallagher/blob/645861934369261268fe14f96f355be0be962c37/app.rb#L41 any numeric/blank input triggers the exception and displays an error page. 
Gradescope says I have unhandled responses for numeric/blank inputs.
Any advice is most welcome. I have tried 'rescuing' the error but no dice. (it works if I disable the raise argument error but im guessing this will fail a test in the game logic then..)

Regards

David.

**Comment by john-french** [comment]
HHey @d-gallagher. Haven't had a chance to run it myself but it looks like the structure of the exception handling isn't right. It's like a `try catch` block in Java, as in 
```java
try 
    something
catch SomeException
   do error handling stuff
```

So in Ruby it'll be 
```ruby
begin
   something
rescue ArgumentError
   do error handling stuff
```
You'll need to call the `guess` method inside the `begin` block.

**Comment by d-gallagher** [comment]
Hi John,

Thanks for getting back to me on that. 
I should have seen the similarity betweet a try catch and the begin blocks. All sorted now.

Muchas gracias!

David.
